const BookingData = [
    {
        id: '1',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '2',
        image: require('./kauai-ikenalani.png'),
        name: 'Pool Services',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '3',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '4',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '5',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '6',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '7',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '8',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '9',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },
    {
        id: '10',
        image: require('./kauai-ikenalani.png'),
        name: 'Home Cleaning',
        time: 'Afternoon',
        date: 'Thursday, 19 June',
        bugget: '400$',
    },

]

export default BookingData